databases:
  - name: blogproj
    databaseName: blogproj
    user: blogproj

services:
  - type: web
    name: blogproj
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn blogproj.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blogproj
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4