# Generated by Django 3.2 on 2022-08-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
